language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g grunt-cli'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'sleep 3'
deploy:
  provider: openshift
  user: "eysteinbye@gmail.com"
  password: "werwer" # can be encrypted
  domain: "showmeapp"
  app: prod